/**
 * Created by jo.chan on 2016/10/31.
 */
//
// export const FETCH_BANNER_SUCCESS = 'FETCH_BANNER_SUCCESS'


export const SUCCESS_REQUEST_SCROLLPIC = 'SUCCESS_REQUEST_SCROLLPIC'

export const SUCCESS_REQUEST_SCROLLPICMIDDLE ='SUCCESS_REQUEST_SCROLLPICMIDDLE'

export const SUCCESS_REQUEST_NOTICE = 'SUCCESS_REQUEST_NOTICE'


export const SUCCESS_REQUEST_RECENTGAMES ='SUCCESS_REQUEST_RECENTGAMES'

export const SUCCESS_REQUEST_HOT = 'SUCCESS_REQUEST_HOT'

export const SUCCESS_REQUEST_NEW = 'SUCCESS_REQUEST_NEW'

export const SUCCESS_REQUEST_NEWS = 'SUCCESS_REQUEST_NEWS'

export const SUCCESS_REQUEST_GAMEZONE = 'SUCCESS_REQUEST_GAMEZONE'

export const SUCCESS_REQUEST_GAMEDETAIL = 'SUCCESS_REQUEST_GAMEDETAIL'
