/**
 * Created by jo.chan on 2016/10/31.
 */


export const SUCCESS_REQUEST_GIFT = 'SUCCESS_REQUEST_GIFT'

export const SUCCESS_REQUEST_DAY = 'SUCCESS_REQUEST_DAY'

export const SUCCESS_REQUEST_WEEK = 'SUCCESS_REQUEST_WEEK'

// export const SUCCESS_REQUEST_BASEINFO = 'SUCCESS_REQUEST_BASEINFO'
